version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "N5challenge-enzo"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
    ports:
      - "1433:1433"

  n5-web-api:
    image: ${DOCKER_REGISTRY-}n5webapi
    build:
      context: .
      dockerfile: N5-Web-Api/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.11
    environment:
        - discovery.type=single-node
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - esdata:/usr/share/elasticsearch/data

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  esdata:

networks:
  default:
    driver: bridge